export const NUMBER_INCREMENT = "NUMBER/NUMBER_INCREMENT";
export const NUMBER_DECREMENT = "NUMBER/NUMBER_DECREMENT";
export const NUMBER_RESET = "NUMBER/NUMBER_RESET";
export const ITEM_ADD = "ITEM/ITEM_ADD";
export const ITEM_REMOVE = "ITEM/ITEM_REMOVE";
export const SHOW_LOADER = "APP/SHOW_LOADER";
export const HIDE_LOADER = "APP/HIDE_LOADER";
export const GET_USERS = "APP/GET_USERS";
